<br>
<h1>Debitar Saldo</h1>
<br>

<div class="alert alert-success" role="alert">
    O saldo atual de <?=$person['name']?> é de R$ <?= number_format($balance, 2, ",", ".")?>
</div>
<form method="POST" id="addForm">
    <input type="hidden" id="id" value="<?=$person['id']?>">
    <input type="hidden" id="balance" value="<?=$balance;?>">
    <div class="row">
        <div class="col-md-6">
            <label for="name" class="col-sm-2 col-form-label">Nome</label>
            <input type="text" maxlength="100" class="form-control required" id="name" name="name" 
                placeholder="Informe o nome da pessoa" value="<?=$person['name']?>" disabled>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-6">
            <label for="cpf" class="col-sm-2 col-form-label">CPF</label>
            <input type="text" maxlength="11" class="form-control required" id="cpf" name="cpf" 
                placeholder="Informe o CPF" value="<?=$person['cpf']?>" disabled>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="cpf" class="col-sm-2 col-form-label">Valor</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">R$</span>
                </div>
                <input type="text" class="form-control required numeric" id="value" name="value" placeholder="0,00">
            </div>
            
        </div>
    </div>
    <br>
    
    <br>
    <div class="row">
        <div class="col-12">
            <button type="button" class="btn btn-primary" id="saveButton">Debitar</button>
        </div>
    </div>
</form>

<script>
    $(document).ready(function(){
        $("#cpf").mask('999.999.999-99');
        $("#value").mask('000.000.000.000.000,00', {reverse: true});
    })

    $("#saveButton").click(function(){
        var id = $("#id").val();
        var value = $("#value").val().replaceAll('.', '').replaceAll(',', '.');

        if(id > 0 && value > 0){
            validateRequiredFields();

            $.ajax({
                type: "post",
                url: "/transactions/debit",
                data: {
                    from : id,
                    value : value
                },
                dataType: "json",
            }).done(function (response) {
                if(response.response){
                    Swal.fire({
                        icon: 'success',
                        title: 'Aeee',
                        text: response.message,
                    }).then(function(){
                        window.location = "/";
                    })
                }else{
                    Swal.fire({
                        icon: 'warning',
                        title: 'Ihhh',
                        text: response.message
                    });
                }
            }).fail(function (jqXHR, textStatus) {
                Swal.fire({
                    icon: 'error',
                    title: 'Ahhh :(',
                    text: 'Ocorreu um erro no servidor, tente novamente mais tarde.',
                })
            });
        }else{
            validateRequiredFields();

            Swal.fire({
                icon: 'warning',
                title: 'Opaa',
                text: 'Preencha os campos obrigatórios.'
            })
        }
    });

    function validateRequiredFields(){
        $("#addForm").find('.required').each(function() {
            if($(this).val() == "" || ($(this).hasClass('numeric') && $(this).val() <= 0)){
                $(this).addClass("is-invalid");
            }else{
                $(this).removeClass("is-invalid");
            }
        });
    }

</script>